Areas/Admin/Controllers/PhieuXuatKhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class PhieuXuatKhoController : Controller
    {
        // GET: Admin/PhieuXuat
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyPhieuXuatKho()
        {
            return View();
        }
        public ActionResult ChiTietPhieuXuatKho()
        {
            return View();
        }
        public ActionResult XemLichSu()
        {
            return View();
        }
        public ActionResult DuyetPhieuXuatKho()
        {
            return View();
        }
        public ActionResult TuChoiPhieuXuatKho()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: Admin/TrangChu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyTKAdmin()
        {
            return View();
        }
        public ActionResult ThemTKAdmin()
        {
            return View();
        }
        public ActionResult XoaTKAdmin()
        {
            return View();
        }
    }
}

Areas/Staff/Controllers/PhieuXuatKhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Staff.Controllers
{
    public class PhieuXuatKhoController : Controller
    {
        // GET: Staff/PhieuXuatKho
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ChiTietPhieuXuatKho()
        {
            return View();
        }
        public ActionResult ThemPhieuXuatKho()
        {
            return View();
        }
        public ActionResult CapNhatPhieuXuatKho()
        {
            return View();
        }
        public ActionResult ThuHoiPhieuXuatKho()
        {
            return View();
        }
    }
}

Areas/Staff/Views/PhieuXuatKho/CapNhatPhieuXuatKho.cshtml
@{
    ViewBag.Title = "CapNhatPhieuXuatKho";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Cập Nhật Phiếu Xuất Kho</span></div>
        <div class="content-main mt-10 w-clear">
            <div class="nhadatnoibat_wrap_itemOne item_knbat">
                Nhập Thông Tin
            </div>
            <form method="post">
                <div class="mt-2 mb-3 d-flex justify-content-center">
                    <input type="submit" class="btn btn-primary mr-2" name="submit" id="submit" value="Cập Nhật">
                    <a href="@Url.Action("QuanLyPhieuXuatKho","TrangChu")" class="btn btn-primary ml-2">Trở Về</a>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Staff/Views/PhieuXuatKho/ChiTietPhieuXuatKho.cshtml
@{
    ViewBag.Title = "ChiTietPhieuXuatKho";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Chi Tiết Phiếu Xuất Kho</span></div>
        <div class="content-main mt-10 w-clear">
            <div class="nhadatnoibat_wrap_itemOne item_knbat">
                Thông Tin
            </div>
            <div class="mt-2 mb-3 d-flex justify-content-center">
                <a href="@Url.Action("QuanLyPhieuXuatKho","TrangChu")" class="btn btn-primary ml-2">Trở Về</a>
            </div>
        </div>
    </div>
</div>

Areas/Staff/Views/PhieuXuatKho/ThemPhieuXuatKho.cshtml
@{
    ViewBag.Title = "ThemPhieuXuatKho";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Thêm Phiếu Xuất Kho</span></div>
        <div class="content-main mt-10 w-clear">
            <div class="nhadatnoibat_wrap_itemOne item_knbat">
                Nhập Thông Tin
            </div>
            <form method="post">
                <div class="mt-2 mb-3 d-flex justify-content-center">
                    <input type="submit" class="btn btn-primary mr-2" name="submit" id="submit" value="Thêm">
                    <a href="@Url.Action("TrangChu","TrangChu")" class="btn btn-primary ml-2">Trở Về</a>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Staff/Views/PhieuXuatKho/ThuHoiPhieuXuatKho.cshtml
@{
    ViewBag.Title = "ThuHoiPhieuXuatKho";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Thu Hồi Phiếu Xuất Kho</span></div>
        <div class="content-main mt-10 w-clear">
            <div class="nhadatnoibat_wrap_itemOne item_knbat">
                Thông Tin
            </div>
            <form method="post">
                <div class="mt-2 mb-3 d-flex justify-content-center">
                    <input type="submit" class="btn btn-primary mr-2" name="submit" id="submit" value="Thu Hồi">
                    <a href="@Url.Action("QuanLyPhieuXuatKho","TrangChu")" class="btn btn-primary ml-2">Trở Về</a>
                </div>
            </form>
        </div>
    </div>
</div>