Areas/Admin/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: Admin/NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            return RedirectToAction("QuanLyTKAdmin", "TrangChu", new { area = "Admin" });
        }
        public ActionResult DangXuat()
        {
            return RedirectToAction("Index", "Home", new { area = "" });
        }
        public ActionResult ThongTinCaNhan()
        {
            return View();
        }
        public ActionResult CapNhatThongTinCaNhan()
        {
            return View();
        }
        public ActionResult DoiMatKhau()
        {
            return View();
        }
        public ActionResult QuenMatKhau()
        {
            return View();
        }
    }
}

Views/Shared/_LayoutIndex.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Quản Lý Kho</title>

    <link rel="icon" type="image/x-icon" href="~/Scripts/Layout/LayoutIndex/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/Scripts/Layout/LayoutIndex/styles.css" rel="stylesheet" />

</head>
<body>
    <header class="py-5">
        <div class="container px-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center my-5">
                        <h1 class="display-5 fw-bolder text-black mb-2">Chọn Vai Trò Của Bạn</h1>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="@Url.Action("DangNhap","NguoiDung",new { Area = "Admin" })">Quản Trị</a>
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="@Url.Action("DangNhap","NguoiDung",new { Area = "Staff" })">Nhân Viên</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>