Areas/Admin/Controllers/PhieuNhapKhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class PhieuNhapKhoController : Controller
    {
        // GET: Admin/PhieuNhap
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyPhieuNhapKho()
        {
            return View();
        }
        public ActionResult ChiTietPhieuNhapKho()
        {
            return View();
        }
        public ActionResult XemLichSu()
        {
            return View();
        }
        public ActionResult DuyetPhieuNhapKho()
        {
            return View();
        }
        public ActionResult TuChoiPhieuNhapKho()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/PhieuXuatKhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class PhieuXuatKhoController : Controller
    {
        // GET: Admin/PhieuXuat
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyPhieuXuatKho()
        {
            return View();
        }
        public ActionResult ChiTietPhieuXuatKho()
        {
            return View();
        }
        public ActionResult XemLichSu()
        {
            return View();
        }
        public ActionResult DuyetPhieuXuatKho()
        {
            return View();
        }
        public ActionResult TuChoiPhieuXuatKho()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: Admin/TrangChu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyTKAdmin()
        {
            return View();
        }
        public ActionResult ThemTKAdmin()
        {
            return View();
        }
        public ActionResult XoaTKAdmin()
        {
            return View();
        }
    }
}

Areas/Staff/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Staff.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: Staff/TrangChu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TrangChu()
        {
            return View();
        }
        public ActionResult QuanLyPhieuXuatKho()
        {
            return View();
        }
        public ActionResult QuanLyPhieuNhapKho()
        {
            return View();
        }
    }
}

Areas/Staff/Views/TrangChu/QuanLyPhieuNhapKho.cshtml
@{
    ViewBag.Title = "QuanLyPhieuNhapKho";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Quản Lý Phiếu Nhập Kho</span></div>
        <div class="box_layout baidang_layout">
            <div class="baidang-slide">
                <div class="nhadatnoibat_wrap_itemOne item_knbat">
                    <div class="nhadatnoibat_wrap_itemOnePictures">
                    </div>
                    <div class="nhadatnoibat_wrap_itemOneInfo">
                        <div class="nhadatnoibat_wrap_itemOneInfoTitle">
                            <a href="@Url.Action("ChiTietPhieuNhapKho","PhieuNhapKho", new { id = 0 })">Mã : 00000000</a>
                        </div>
                        <div class="d-nhandat-info">
                            <div class="nhadatnoibat_wrap_itemOneInfo21 text-primary text-price">
                                <span>Chưa Duyệt</span>
                            </div>
                            <div class="nhadatnoibat_wrap_itemOneInfo21">
                                5 sản phẩm
                            </div>
                        </div>
                        <div class="nhadatnb-user">
                            <div class="d-flex align-items-center">
                                <a href="@Url.Action("CapNhatPhieuNhapKho","PhieuNhapKho", new { id = 0 })" class="btn btn-primary mr-2">Cập Nhật</a>
                                <a href="@Url.Action("ThuHoiPhieuNhapKho","PhieuNhapKho", new { id = 0 })" class="btn btn-primary ml-2">Thu Hồi</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Staff/Views/TrangChu/QuanLyPhieuXuatKho.cshtml
@{
    ViewBag.Title = "QuanLyPhieuXuatKho";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Quản Lý Phiếu Xuất Kho</span></div>
        <div class="box_layout baidang_layout">
            <div class="baidang-slide">
                <div class="nhadatnoibat_wrap_itemOne item_knbat">
                    <div class="nhadatnoibat_wrap_itemOnePictures">
                    </div>
                    <div class="nhadatnoibat_wrap_itemOneInfo">
                        <div class="nhadatnoibat_wrap_itemOneInfoTitle">
                            <a href="@Url.Action("ChiTietPhieuXuatKho","PhieuXuatKho", new { id = 0 })">Mã : 00000000</a>
                        </div>
                        <div class="d-nhandat-info">
                            <div class="nhadatnoibat_wrap_itemOneInfo21 text-primary text-price">
                                <span>Chưa Duyệt</span>
                            </div>
                            <div class="nhadatnoibat_wrap_itemOneInfo21">
                                3 sản phẩm
                            </div>
                        </div>
                        <div class="nhadatnb-user">
                            <div class="d-flex align-items-center">
                                <a href="@Url.Action("CapNhatPhieuXuatKho","PhieuXuatKho", new { id = 0 })" class="btn btn-primary mr-2">Cập Nhật</a>
                                <a href="@Url.Action("ThuHoiPhieuXuatKho","PhieuXuatKho", new { id = 0 })" class="btn btn-primary ml-2">Thu Hồi</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Staff/Views/TrangChu/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Areas/Staff/Views/Shared/_LayoutStaff.cshtml";
}

<div class="wrap-main  w-clear">
    <div class="box_layout padding-box">
        <div class="title-main"><span>Trang Chủ</span></div>
        <div class="content-main mt-10 w-clear">
            <div class="mt-2 mb-3 d-flex justify-content-center">
                <a href="@Url.Action("ThemPhieuNhapKho","PhieuNhapKho")" class="btn btn-primary mw-auto">
                    <span>Tạo Phiếu Nhập Kho</span>
                </a>
            </div>
            <div class="mt-2 mb-3 d-flex justify-content-center">
                <a href="@Url.Action("ThemPhieuXuatKho","PhieuXuatKho")" class="btn btn-primary mw-auto">
                    <span>Tạo Phiếu Xuất Kho</span>
                </a>
            </div>
            
        </div>
    </div>
</div>